<ips:template parameters="$members, $config" />
{{if \is_array($members) && \count($members)}}

<h3 class='ipsWidget_title'>{lang="steam_title"}</h3>
<div class='ipsPad'>

		{{foreach $members as $id => $member}}
			<div class='ipsColumns'>
				<div class='ipsColumn ipsColumn_veryNarrow'>
				    <a href='{$member->profileurl}' target='_blank'><img src='https://avatars.steamstatic.com/{$member->avatarhash}_medium.jpg' alt='{$member->personaname}' class='ipsSpacer_bottom ipsUserPhoto_small'/></a>
				</div>
				<div class='ipsColumn ipsColumn_fluid'>
				    <span class='ipsTruncate ipsTruncate_line'>
						{{if $member->gameextrainfo || $member->gameid }}
							<strong class='ipsOnlineStatus ipsOnlineStatus_online' data-ipsToolTip {{if $member->gameextrainfo }}title='{lang="steam_playing"}: {$member->gameextrainfo}'{{endif}}> <i class='fa fa-circle'></i></strong>
						{{else}}
							<strong class='ipsOnlineStatus' style="color: #86b5d9;" data-ipsToolTip title="{lang="steam_status_{$member->personastate}"}"> <i class='fa fa-circle'></i></strong>
						{{endif}}
				    	<a href='{url="app=core&module=members&controller=profile&id={$member->member_id}&tab=node_steam_steamprofile"}' target='_blank'>{$member->personaname}</a>
				    </span><br/>

				    {{if isset($member->games) && ($member->total_count > 0) && $config['steamIndex2weeks']}}
					    <div class='ipsSpacer_top ipsSpacer_half'>
					    	<ul class='ipsGrid'>
							    {{foreach $member->getRecent(6) as $_id => $game }}
							        <li class='ipsGrid_span2'>
							        	<img src="https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/{$game['appid']}/{$game['img_icon_url']}.jpg" data-ipsToolTip alt="{$game['name']}" title="{$game['name']}: {expression="round($game['playtime_2weeks'] / 60, 1)"} {lang="steam_2weeks"}" height='28px' width='28px'/>
							        </li>
								{{endforeach}}
						     </ul>
						</div>
					{{else}}
						{{if $member->playtime_2weeks}}
							<span class='ipsType_light'>{expression="round(($member->playtime_2weeks / 60), 1)"} {lang="steam_2weeks"}</span><br />
						{{else}}
							<span class='ipsType_light'>{lang="steam_noplaytime"} {lang="steam_2weeks"}</span><br />
						{{endif}}
					{{endif}}
				</div>
			</div>
	  	{{endforeach}}

</div>
{{endif}}