<ips:template parameters="$group, $profiles, $config, $vert" />
<h3 class='ipsWidget_title'>{$group->name}</h3>
<div class="ipsWidget_inner st_minHeight ipsPad{{if $vert}} ipsPad_half{{endif}}">
	{{if $vert}}
	<div class="ipsType_center">
		<a href="{$group->url()}" class="ipsUserPhoto ipsUserPhoto_medium">
			<img src="{$group->avatarFull}" />
		</a>
	</div>
	{{else}}
	<div class="ipsPos_left ipsSpacer st_hPhoto">
		<a href="{$group->url()}" class="ipsUserPhoto ipsUserPhoto_large">
			<img src="{$group->avatarFull}" />
		</a>
		<div class="ipsType_center ipsSpacer_top ipsSpacer_half">
			<div class="">
				<a href="{$group->url()}" class="ipsButton ipsButton_alternate ipsButton_veryVerySmall ipsSpacer_bottom ipsSpacer_half st_hJoin">{lang="st_joinGroup"}</a>
			</div>
			<div class="">
				<a href="{$group->chat()}" class="ipsButton ipsButton_alternate ipsButton_veryVerySmall st_hJoin">{lang="st_joinChat"}</a>
			</div>
		</div>
	</div>
	<div class="ipsPos_right ipsType_center st_hCounts">
		<div class="">
			<span class="ipsType_minorHeading">{lang="st_members"}</span>
			<br />
			<span class="ipsType_small ipsType_neutral">{number="$group->memberCount"}</span>
		</div>
		<div class="ipsSpacer_both ipsSpacer_half st_inGame">
			<span class="ipsType_minorHeading st_inGame">{lang="st_inGame"}</span>
			<br />
			<span class="ipsType_small">{number="$group->membersInGame"}</span>
		</div>
		<div class="ipsSpacer_both ipsSpacer_half st_online">
			<span class="ipsType_minorHeading st_online">{lang="st_online"}</span>
			<br />
			<span class="ipsType_small">{number="$group->membersOnline"}</span>
		</div>
		<div class="ipsSpacer_bottom ipsSpacer_half">
			<span class="ipsType_minorHeading">{lang="st_inChat"}</span>
			<br />
			<span class="ipsType_small ipsType_neutral">{number="$group->membersInChat"}</span>
		</div>
	</div>
	{{endif}}
	<div class="ipsSpacer_both ipsType_center">
		<span class="ipsType_large ipsType_reset">{$group->headline}</span>
	</div>
	{{if $config['steamDescription']}}
	<div class="ipsSpacer_bottom ipsType_center" data-ipsTruncate data-ipsTruncate-type='hide' data-ipsTruncate-size="{$config['steamLimit']} lines">
		<span class="ipsType_medium">{$group->summary|raw}</span>
	</div>
	{{endif}}
	{{if $config['steamShowMembers']}}
	<div class="ipsType_center">
		{{foreach $profiles as $id => $p}}
			{{if $id >= $config['steamUserCount']}}
				{{break;}}
			{{endif}}

			<a href="{$p->author()->url()->setQueryString(array('tab' => 'node_steam_steamprofile'))}" class="ipsUserPhoto ipsUserPhoto_mini" target="_blank">
				<img src="https://avatars.steamstatic.com/{$p->avatarhash}_medium.jpg" title="{$p->personaname}" alt="{$p->personaname}"data-ipsToolTip />
			</a>
		{{endforeach}}

	</div>
	{{endif}}
	{{if $vert}}
	<hr class="ipsHr">
	<div class="ipsGrid ipsType_center">
		<div class="ipsGrid_span3">
			<span class="ipsType_minorHeading">{lang="st_members"}</span>
			<br />
			<span class="ipsType_small ipsType_neutral">{number="$group->memberCount"}</span>
		</div>
		<div class="ipsGrid_span3 st_inGame">
			<span class="ipsType_minorHeading st_inGame">{lang="st_inGame"}</span>
			<br />
			<span class="ipsType_small">{number="$group->membersInGame"}</span>
		</div>
		<div class="ipsGrid_span3 st_online">
			<span class="ipsType_minorHeading st_online">{lang="st_online"}</span>
			<br />
			<span class="ipsType_small">{number="$group->membersOnline"}</span>
		</div>
		<div class="ipsGrid_span3">
			<span class="ipsType_minorHeading">{lang="st_inChat"}</span>
			<br />
			<span class="ipsType_small ipsType_neutral">{number="$group->membersInChat"}</span>
		</div>
	</div>
	<div class="ipsType_center ipsPad ipsPad_half">
		<span class="st_vButton">
			<a href="{$group->url()}" class="ipsButton ipsButton_alternate ipsButton_veryVerySmall st_hJoin">{lang="st_joinGroup"}</a>
		</span>
		<span>
			<a href="{$group->chat()}" class="ipsButton ipsButton_alternate ipsButton_veryVerySmall st_hJoin">{lang="st_joinChat"}</a>
		</span>
	</div>
	{{endif}}
</div>